FROM node:lts-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
#COPY . .
COPY src src
COPY src/environments/environment.dev.ts src/environments/environment.ts
COPY angular.json angular.json
COPY .eslintrc.json .eslintrc.json
COPY tsconfig.app.json tsconfig.app.json
COPY tsconfig.json tsconfig.json
RUN npm run build-dev

FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]