export const projectOption = {
  // HEADERS
  lang: 'lg',
  userKey: 'u',
  userObj: 'h-uo',
  structureObj: 's',
  tokenKey: 'h_auth_token',
  userRolesKey: 'h_r',
  userSousRolesKey: 'h_sr',
  rootLink: '/',
  firstLink: '/dashboard',
  loginLink: '/login',
  errorLink: '/error',
  societeLink: '/societe',
  expiredConnexionMessage:
    'La connexion a expirée, réconnectez vous pour continuer',
  errorMessage: "L'opération n'a pas été effectuée avec succès!",
  succesMessage: 'Opération éffectuée avec succès!',
  emailPattern: '^[a-z0-9._%+-]+@[a-z0-9.-]+.[a-z]{2,4}$',
  phonePattern: '[0-9]*',
  userActionsKey: 'a',
  reunionKey: 'E_REUNION_KEY',
  helpLink: '#',
  newPassword: '/newPassword/',
};
